name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27

      - name: Install backend dependencies
        run: bun install

      # If your frontend needs to be built separately:
      - name: Install frontend dependencies
        run: bun install
        working-directory: ./frontend

      - name: Build frontend
        run: bun run build
        working-directory: ./frontend

      # If your backend build depends on the frontend output, add a step to copy/move files as needed

      # - name: Build backend
      #   run: bun run build

      # Optionally run tests
      # - name: Run tests
      #   run: bun test

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v1
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}